### ISSUE TITLE
Question: Strong-Copyleft Terms

### ISSUE THREAD

**Issue by bhilburn** [licensezero/parity-public-license#13]
IANAL.

Per the README, the Parity license is intended to provide a very strong copyleft license. To that end, the current version of the Parity license uses the active word `Release` in requirements clauses, referring of course to the release of source code.

However, the word `release` is never defined in terms of the license. By this, I mean it seems to me that someone could interpret `release` to simply mean publishing the source code, **but not providing a license under which to use it**. It's worth noting, for example, that [Github's ToS](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership) explicitly say if no license is specified, this is the default case (i.e., you can fork/view a repo, but have no other rights). 

In looking for a clause that specifically requires the `release` to occur under the Parity license (or something similar), I did see this:

```
To release source code, publish the preferred form for making
changes through a freely accessible distribution system widely
used for similar source code, and license additional work on
terms at least as permissive as this license.
```

But that only seems to apply to **additional** work made to the original, not to the original itself.

Is this concern valid, or am I misunderstanding how the language works?

**Comment by kemitchell** [comment]
@bhilburn Again, excellent feedback!

Parity is stronger than AGPL, in that it requires sharing alike in more situations. For example, Parity requires sharing source code of programs built with transpilers, under rule 3.

But in another dimension, Parity is _less_ stringent than AGPL, in that once it does require sharing alike, it does not dictate the exact license terms that need to apply to shared code, or require that all license terms for a project as a whole be the same. For example, if you release a library under Parity and I add a feature to it, rule 1 requires that I publish my changes and license them, but I could license my changes under a more permissive license, like [Charity](https://licensezero.com/licenses/charity), rather than Parity.

As for your original, Parity-licensed code, I have no legal right to change the license terms that apply to it. You own the copyright, not I. And the Parity license doesn't give me any right to sublicense your Parity code under different terms. In fact, rule 4 of Parity requires that I make sure others know that your code is Parity-licensed:

> 4. Ensure everyone who gets a copy of this software from you, in source code or any other form, gets the text of this license and the copyright and source notices above.

I added the words "additional work" to the instructions for release in c9c8d842023549aa2b6e1ef1a2b8086c0517f476 specifically to avoid any implication that Parity gives anyone the right to change license terms for source code licensed on its terms.

License compatibility is a concern for any project that incorporates code under different license terms. Even administrative conditions above giving notice and credit can conflict.  But historically, license compatibility pain has been felt mostly from licenses like GPL that require sharing alike under _the same terms_. Every license that says, in effect, "the whole project must be under _my_ terms" butts heads with every other license that says anything similar.

Parity doesn't build in any automatic yield-to-GPL mechanism for GPL compatibility, like [EPL 2.0](https://www.eclipse.org/legal/epl-2.0/)'s "Form of Secondary Licenses Notice". But on the other hand, it doesn't create the kind of inherent compatibility conflict that GPL does.

**Comment by bhilburn** [comment]
Thanks for the response! So, this is the specific item that gets to the heart of my question, I think (emphasis mine):

> But in another dimension, Parity is less stringent than AGPL, in that once it does require sharing alike, it does not dictate the exact license terms that need to apply to shared code, or require that all license terms for a project as a whole be the same. For example, if you release a library under Parity and I add a feature to it, **rule 1 requires that I publish my changes and license them**, but I could license my changes under a more permissive license, like Charity, rather than Parity.

Rule 1 reads:
>1. Release source code for changes you make to this software.

By my reading, that does not require someone who makes downstream changes to release their code licensed in a way that allows anyone else to use them. Example:

1. Alice releases project-foo under Parity
2. Bob adds a new feature to project-foo. Per Rule #1 of the Parity license, he publishes his version of project-foo including his change, but **does not provide a license for his change**, thus preventing their use by anyone that isn't Bob - even though everyone can **see** that he's made the changes.

My confusion is that I don't see where the Parity license prevents that case. The GPL / AGPL, for example, would require that those changes also be released under the GPL / AGPL, thereby propagating the license terms.

Again, I'm playing armchair lawyer, here, but am interested in understanding how my interpretation is flawed :)

**Comment by bhilburn** [comment]
>     Do you think the phrase "release source code" is confusing, since that usually means just publishing code, and Parity is trying to define it to mean both publishing and licensing?
> 
>     A fix here might be to us a new phrase. Perhaps "share source code" or "contribute source code"?

When I read `release source code`, my assumption is that it makes no promise as to the license under which it is delivered. Especially since things like Github ToS codify a default state of "source available but proprietary" unless something is stated otherwise, I think that's the only safe assumption that can be made. My interpretation of the word `share` is the same.

I've never seen someone use `contribute` in that context, but if I did, my interpretation would mean that I'm required to attempt to upstream it, which creates a burden for both the licensee and licensor that would almost certainly be a barrier to adoption, IMO.

>     Is the trouble with "additional work"? Perhaps you read that language to give Bob an out. If so, might you try to help me read it as you do?

So, actually, having read and re-read that clause many times, now, I think my real confusion comes from two things: the phrase `additional work`, and the word `permissive`.

#### `permissive`
Part of my misunderstanding, I think, is that the word `permissive` will be filtered by the reader's specific philosophical approach to F/OSS. The FSF, for example, views the GPL / AGPL as providing `freedom` and `protecting the freedom of users`, whereas I view them as **restricting** freedom to achieve a particular goal. I would never call a strong copyleft license that requires source release `permissive`, so when I read, 

> and license additional work on terms at least as permissive as this license.

what does `at least as permissive as this license` mean, when this is (according to my perspective) one of the least permissive licenses I've ever seen? I'm just not sure what to make of it.

_NB: I want to be clear that by saying this `is one of the least permissive licenses I've ever seen`, I'm not saying that's a bad thing. Licenses are tools, and I believe in using the best tool for the job - sometimes that means proprietary, sometimes that means permissive, sometimes that means AGPL, etc,._

#### `additional work`

To best explain why this phrasing confused me, I'll demonstrate my reading with some algebraic substitution. For the purposes of this discussion, let's assume that you and I both agree on how to interpret `permissive`, per your definition.

Let's take this phrase:

> 2. If you run or combine this software with other software in
> any larger program, [[release all source code for that program]].

Substituting this definition for "release source code",

> To release source code, publish the preferred form for making
> changes through a freely accessible distribution system widely
> used for similar source code, and license additional work on
> terms at least as permissive as this license.

Into the `[[...]]` above, we get:

> 2. If you run or combine this software with other software in
> any larger program, publish the preferred form for making
> changes through a freely accessible distribution system widely
> used for similar source code, and license additional work on
> terms at least as permissive as this license.

Okay, so breaking the above down, if I combine a Parity-licensed library with other software, _I am required to publish the source code somewhere_, and **then** license _additional work_ under Parity / Charity. What is that `additional work` relative to the combined program? Is that relative to the original Parity-licensed work, or my combined work?

For example, let's say you:

1. Grab a Parity-licensed lib, `project-foo` and add a new feature to it, creating `project-foo-bar`.
2. Build software, `project-snafu`, that uses `project-foo-bar`.
3. Release the source code for `project-snafu`, but under a proprietary license.
4. Provide a license for **only the additional work** made to `project-foo` to create `project-foo-bar`.

Would I be in compliance with that clause? Obviously your answer, and the intent of the license, is **no**, but my untrained-legal mind read that as a gap. Perhaps everyone that knows what they are doing, though, would arrive at the same conclusion when reading that?

Anyway, I hope that helps! Sorry if my prose is clunky, at times, but hopefully it's follow-able =)

**Comment by kemitchell** [comment]
@bhilburn, I know that post took a while to write, but I think it's having its intended effect. I'm starting to see through your eyes a bit.

I will send a PR with changes to the licensing instructions language, and mention you. I think that will better address the point of your hypothetical.

**Comment by kemitchell** [comment]
@bhilburn #14 tries to address your concerns about "additional work".

At the same time, I'm reluctant to move on "permissive". I believe you're absolutely right that in the arc of open software licenses, Parity is at an extreme point across the spectrum from MIT, BSD, and Apache. But the plain meaning of "permissive" is right on point. From Cambridge:

> allowing a wide range of choices, esp. in an area where there have traditionally been rules that had to be obeyed:
>
> _Their neighbors thought they were too permissive with their children, letting them stay up so late at night._

I like that "permissive" in Parity makes clear that users can indeed use licenses like MIT and BSD to meet the release requirement. I also like that "permissive" in Parity calls out that while open source jargon might point to Parity being anything but a permissive license, in the grant scheme of things, it is still an extraordinarily generous license that inverts the default legal rule of "all rights reserved".

Ideally, I'd trade away that latter "zinger" factor for terms of least surprise. But I can't find any word close in meaning to "permissive" that's as specific---"generous" would be just as short, but even fuzzier---and I don't think there's an effective middle ground between picking the right word and offering something like a functional definition of an open source license. That latter is a sometimes and recurring project of mine, but even if it succeeds, I don't think I'll paste the result into Parity.

**Comment by bhilburn** [comment]
@kemitchell - I completely understand your perspective regarding use of the word `permissive`, and appreciate your goals in doing so. Thanks for explaining! Allow me to provide one more point on this topic from my perspective:

As an OSS maintainer, one of my goals in using Parity would be to guarantee that if someone extends my project, I get (a) the source code of those changes and (b) the right to use them in my project. It's clear that you are trying to cover that case both with the license as a whole, and specifically here with the word `permissive`.

But, let's say someone grabs my project, extends it, and decides to release it under a different license. How about this one, which I am going to invent on-the-spot (license proliferation lol):
```
                          The UIALMEA Public License

This software is released under the Use It And Leave Me Alone Public License. 

  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION, AND MODIFICATION

 0. You just DO WHAT YOU WANT TO AND LEAVE ME ALONE.
 1. If you redistribute this software with modifications or incorporate it into other software, 
    it must be licensed under the UIALMEA.
```

To many people, the UIALMEA is a more permissive license than Parity. But, its copyleft precludes Parity-licensed projects from incorporating code licensed under it. Thus, from my perspective, it's conceivable that someone could release work based on my Parity-licensed work, firmly believe they are in compliance with the Parity license, and yet I would be unable to incorporate their derivative work back into the project. 

I think that's really the heart of my concern with what I see as the ambiguity of the word `permissive` - with such differing opinions on what is "permissive" and what "freedom" is (relative to software), it seems like a bit of a minefield.

I'm interested in your thoughts on the above, and thanks for your time thus far!

**Comment by kemitchell** [comment]
> I should have checked previous issues before opening this one, hah =)

Not at all. This is a questions repo. It's about the question-and-answer process.

**Comment by kemitchell** [comment]
@bhilburn, FYI, the most recent version of Parity now speaks in terms of "contributing" source code, rather than merely releasing it. I think that should help address some of your concern about misreadings.
