### ISSUE TITLE
Not all source code is software

### ISSUE THREAD

**Issue by bmintz** [licensezero/parity-public-license#18]
The license mentions "this software" and "source code", implying that the covered work must be software. However, some juries do not interpret e.g. firmware or Hardware Description Language code to be software. Ideally this license should be usable for all sorts of source code.

**Comment by kemitchell** [comment]
@bmintz if you apply Parity to firmware or HDL with an unambiguous licensing statement, like a source comment that says “Copyright Ben Mintz. Licensed under the terms of The Parity Public License x.y.z”, I suspect it would be clear what you are licensing, and that you consider it software.

Are you familiar with any firmware or HDL under BSD or MIT licenses, which also say “software”?

I imagine the kind of jury finding you allude to might come up in a patent context. If in contract, at least under US law, the court would look to the facts of the particular situation to try to resolve vague or unambiguous language. It wouldn’t simply apply the definition implied by a jury finding in a different case.
