### ISSUE TITLE
Question: Spread when used for interpreters / compilers

### ISSUE THREAD

**Issue by MoritzMaxeiner** [licensezero/parity-public-license#21]
IANAL.

Clause 3. of the license currently states
```
Contribute all source code for software you develop, deploy,
monitor, or run with this software.
```

My question is how this clause is to be interpreted w.r.t. interpreters/compilers.
As I understand it, were I to write an interpreter (Int) for some programming language (PL) and release it under the current version of the Parity license, this would mean anyone writing a script and having that script be interpreted by Int (i.e. have it `run with this software`) would be required to contribute that script. Is this interpretation correct?

What about compilers? If I were to release a compiler (C) licensed under the current version of the Parity license and some person P used that compiler in their "write -> compile -> debug", would it trigger `develop with this software` and require P to contribute their program?
If not what if the PL accepted by C supports compile time function execution (CTFE), i.e. some fragments of the source code written by P get executed as part of the compilation process to object code (e.g. as part of some meta programming scheme to have source code generate other source code). Would this then trigger `run with this software` and require P to contribute their program?

EDIT: Somewhat related follow up question: Under what license is the parity license itself?
EDIT2: I realize after some more thought that this could be seen as asking for legal advice (not my intent); if you see it that way, feel free to just close.

**Comment by kemitchell** [comment]
The _intent_ of the license is to require contribution of source code for programs in situations like the interpreter and compiler hypotheticals you describe.

I'd be very interested in _your_ opinion of whether rule 3 expresses that intent.

Whether a court of law would enforce that intent, and in what way, are indeed legal questions.

**Comment by MoritzMaxeiner** [comment]
Thank you for clarifying (both what the intention of the license is, and the distinction when it would become a legal question).

In my opinion rule 3 expresses the following (in short: yes):
- Calling[1] a Parity licensed interpreter on some source code S triggers `run with this software` reaching all of S[2]
- Calling[1] a Parity licensed compiler on some source code S triggers `develop with this software` reaching all of S[3]; if CTFE is involved, it additionally triggers `run with this software` reaching only those parts of S that are indeed being run at compile time

I'm somewhat concerned about the `freely accessible` requirement of the distribution, since access to the current `distribution system widely
used for similar source code`, i.e. the _internet_, isn't free in most countries I know of (one needs to pay an ISP for access, not to mention censorship laws), though that's a separate issue.

[1] As defined according to the applicable execution environment; in an ahead of time compilation model this could mean spawning a process, launching a unikernel, etc.; if the callee is itself being interpreted / run in some virtual machine (like the JVM, or some Wasm implementation) this would mean executing the corresponding call instruction.
[2] If the PL in which S is written includes some module system, source code S' for (even indirectly) imported functionality that is run by the interpreter as a result of S being run is also reached (functionality only imported, but not actually used by S is not reached)
[3] A module system here would not result in source code S' for functionality included and (potentially indirectly) used by S being reached, except for functionality that is run in the compiler due to CTFE.

**Comment by kemitchell** [comment]
Thank you very much for this detailed analysis!

The details of how code relates, how it's connected, when it's run or copied or changed, and how, will always be complex, and will always change.  The approach of Parity's plain language is to avoid needless complexity and hassles, by stating its requirements broadly, in such a way that it doesn't matter _how_ we use Parity code to develop and work with other code. The "free for open source" license means "free for open source", and details like static or dynamic linking, library or framework, dev tool or plug-in, don't matter.

Your point on "free" distribution is well taken. I'm not sure if it's worth addressing. The distribution methods we had in mind were free Internet or Web methods, but we didn't want to specify any particular network.
