### ISSUE TITLE
Question: Under which License is the Parity license itself

### ISSUE THREAD

**Issue by MoritzMaxeiner** [licensezero/parity-public-license#23]
Continuing my OT question from https://github.com/licensezero/parity-public-license/issues/21:

Is the Parity License itself available under some license?

**Comment by kemitchell** [comment]
Another good question.

Neither Parity nor any of its variants---Prosperity and Charity under License Zero, a few others, like Posterity, that I've written as experiments---are currently available under any public license.  That being said, I'm _very_ interested in improvements and variations, and have helped a number of folks come up with their own.

If you'd like to propose changes to any of those licenses, please feel free to send pull requests.  If you have an idea for something distinct, just let me know.

**Comment by MoritzMaxeiner** [comment]
Thank you once more for the clarification.

I'll definitely send PRs if I think it'd beneficial to those licenses, but right now I'm still deciding on what triggers[1] I truly want for a compiler project of mine. Once I've nailed those down I think I'll propose something with slightly fewer triggers than Parity.

[1] I really appreciated your "How to Speak Copyleft" blog post on this topic.

**Comment by MoritzMaxeiner** [comment]
@kemitchell I've made a variant of the Changes Back Public License which (I think) covers all my needs, if you want to have a look: https://github.com/MoritzMaxeiner/contribute-public-license
