### ISSUE TITLE
Question on pronoun use in disclaimer

### ISSUE THREAD

**Issue by compleatang** [licensezero/parity-public-license#25]
Two related questions on the [final paragraph](https://github.com/licensezero/parity-public-license/blob/v4.0.0/LICENSE.mustache#L43-L45) of v4.0.0. Perhaps my readings are off and I'm misunderstanding some things. 

**Question 1**: In the disclaimer / as is warranty rep para (final para) Parity currently uses an `I` pronoun which reads awkwardly for a corporate licensee (such as our company). The `I` pronoun is also used in L12 of the v4.0.0 license. There is reads less awkwardly than in the final paragraph (due to Q2 below). However I'm wondering if a bit more clarity for both individual and corporate licensors (by using an `I/we` variable or `Licensor` like noun rather than the `I` pronoun) would it be possible to take a look at that usage. 

**Question 2**: It's also a bit unclear whether the as is warranty rep in the final para is inuring to the benefit of the licensor or the license drafter. It appears that we're currently trying to cover the base of both there, which is fine but currently it reads oddly to me (perhaps I'm alone in this reading) due to a combination of Q1 and also being a corporate licensor.

**Comment by kemitchell** [comment]
For reference, v4.0.0 uses the first person twice:

> If you follow the rules below, you may do everything with this software that would otherwise infringe either my copyright in it, any patent claim I can license that covers this software as of my latest contribution, or both.

>  **This software comes as is, without any warranty at all. As far as the law allows, I will not be liable for any damages related to this software or this license, for any kind of legal claim.**

**Comment by kemitchell** [comment]
I am obviously not the only reader that counts, but I have a bit of trouble reading the warranty disclaimer and damages exclusion to benefit the author of the _license_, as opposed to the one licensing the _software_.

First because the drafter of the license text is never mentioned. I think it would be quite a stretch to read them in, whether as part of an IP license, or as a part or beneficiary of a contract. Contrast licenses that comes with a copyright notice for the license, as in Apache 2.0, or define the drafter as a steward who can release new versions, as in GPLv3.

Second, the warranty disclaimer mentions "[t]his software" only. The license drafter has no implied warranties to disclaim.

Fourth and finally, the damages exclusion mentions both the software and the license, to avoid arguments that it doesn't reach, for example, claims that the licensor claimed IP rights in the work they didn't have.  "I" is the same "I" as in the permission grant.

**Comment by kemitchell** [comment]
You're right that first person singular reads awkwardly for entity licensors. In the end, I chose first and second person over "Licensor" or "Contributor" and "Licensee" or "User" for readability. I expect that use by individual developers will be the "hot path".

I think "we" might read better, without offering any additional clarity. The singular "I" at least tracks the legal fiction or entity legal personhood, though of course that won't be evident to readers without legal background.

There is one more constraint: Unlike other license forms that try to speak for many contributors, collectively, Parity speaks for just one developer. (Of course, each of many contributors to a project can use Parity to express their terms.) That design choice plays into a singular "I" or, if we rewrote the license, singular "Licensor" or "Contributor".

I'm open to ways to improve the situation for entity licensors. @compleatang, do you have something in mind?

**Comment by kemitchell** [comment]
Thinking aloud: The easy patch here might a clarification for the specific case where "I" refers to an entity.

**Comment by compleatang** [comment]
I thought you were off this week :-) ! 

Agree it is probably a stretch to claim that benefit would inure to the license drafter but I was pondering that reading after looking at the changes when upgrading to v4.0.0. On my light of the day reading, I think you're 100% correct that it would be a very big stretch to get to that point.

I had missed that one of the design principles of Parity was the individual contributor portion. Given that principle it does seem logical to stick with `I`. Agree fully that the first|second person reading is significantly more approachable than the third person with titles reading. 

Finally, agree that the resolution could be a clarification where `I` refers to an entity, **or** leave as is and leverage the legal fiction of the corporate personage. I'm happy with either, but just wanted to query. Will close this for now as my question is fully answered! :-)

**Comment by kemitchell** [comment]
I’m still _very_ interested in clarifying who “I” is, especially for entity licensors.

**Comment by compleatang** [comment]
Could it be a mustache if then else statement utilizing I or we depending on whether individual or entity licensee? Or are you thinking an additional definition type sentence?

**Comment by kemitchell** [comment]
Here it is with first person _plural_.

https://github.com/licensezero/parity-public-license/blob/first-person-plural/LICENSE.mustache

Note that "my" also changes to "our".

This will read awkwardly for single licensors.

Still thinking about a way to make this generic without legal style.

**Comment by kemitchell** [comment]
@compleatang on further thought and reflection here, I was wrong.

I _do_ believe that the majority of Parity users, by number of licenses granted, will be individual developers. But the social, dare I say political purpose of Parity cuts straight across natural and legal personhood.  Parity ought to work both for people and for people working through corporations, equally well, just as it works equally well for idealistic developers who believe software _ought_ to be open, and developers (or companies) who want to drive dual-licensing bargains to support their open work.

Both dualities ought to come across in the terms. The readability advantage of first-person pronouns over what boils down to a defined term---I picked "contributor" in #26---is a small price to pay for that benefit.

Your use of Parity was well within the spread of use cases I had in mind for this license. The license ought to work well, without peculiar hitch, for what you want to do. Have a look at #26 if you get a chance.

**Comment by compleatang** [comment]
I've looked and the proposed v5.0.0 in #26 reads much more clearer for our entity licensor and also I like the other bits of cleanup in that iteration. ++ from me.
