### ISSUE TITLE
Is there missing something?

### ISSUE THREAD

**Issue by makkus** [licensezero/parity-public-license#28]
Hi there,

this might very well be just my brain knotting up, but when reading over: 

> To contribute software, publish all its source code, in the
> preferred form for making changes, through a freely accessible
> distribution system widely used for similar source code, and
> license contributions not already licensed to the public on terms
> as permissive as this license accordingly.

I feel there is a slight gap somewhere. I have a hard time explaining myself though. 

Which part does the 'on terms as permissive as this license accordingly' belong to? To 'not already licensed', or 'license contributions'?

Does it tell me to 'license contributions':

- which are not licensed in terms as permissive...

or

- (any contributions that are not already licensed to the public) in a way (on terms) that they are licensed as permissive...

I guess the former, as the 'on' makes less sense otherwise (but I'm not sure, that's where I have an English-as-a-second-language problem, as well as with 'accordingly', as I'm not sure what exactly that refers to. So mabye it's very clear to a native speaker, if that's the case just ignore me.

Either way, if the former, couldn't I choose to license any old way (even less permissive), as long as I license parts that are not licensed at all to the public yet? Or does the accordingly here prevent that? If, is that a strong enough marker?

And if the latter, what about parts that are already licensed to the public?

Does any of this make sense? :-)

P.S. I've read your latest blog post, but didn't get any more clarity on that one point there either...

**Comment by kemitchell** [comment]
```
To contribute software,
  publish all its source code,
  in the preferred form for making changes,
  through a freely accessible distribution system
    widely used for similar source code,
and
license
  contributions
    not already licensed
      to the public
      on terms as permissive as this license
  accordingly.
```

"Accordingly" is tricky.  Can we make it more clear?

The current language may be clear to native English speakers. But I don't want anything in Parity to require native English.  It should make sense to educated non-native readers of English, too.

**Comment by makkus** [comment]
Ha, writing legal text with Python indentation is surprisingly helpful, this makes it much easier to parse for me.

So, the 'overall' instruction is to 'license contributions accordingly, right? And 'accordingly' refers to the 'at-least-as-permissive'-term. Which, in this case does double-duty because it 1) specifies when it is necessary, and 2) also specifies how exactly to do it (because that is not mentioned anywhere else in the license). Did I get that right? 

If, then I think my main problem is that I can't translate this to German without it loosing either the first or second one of those references.

I can't really thing of an elegant way to improve it so it reads more naturally for me. The 'as-permissive'-part would probably need to go into the first part of the sentence too, something like:

> To contribute software, publish all its source code using terms as permissive as this license, in the preferred....

But that'd be ugly, as it would crop up again at the end. So, its' probably better to leave it as it is, I certainly appreciate how Parity tries to encompass a lot while trying to limit the word count as much as possible. And it looks like it's a very personal issue I'm having...

**Comment by jeremy-w** [comment]
Native English speaker here. I (mis)read it the same way. I found myself wondering, “OK, contributions have to be licensed with a Parity-equivalent (on terms yadda yadda), but only if they weren’t already licensed to the public. **Already as of when?** What if they were already licensed using a more restrictive license before my Parity contribution? Now what do I do with new work - does it stay already restrictively licensed, or does it have to follow the Parity-equivalent requirement?”

This also gets kinda weird with dev tools, I think, but I’ll try to write up another issue discussing that soon (example case of aiming a debugger at not-my-program, like Hopper disassembler at an Apple framework).

**Comment by kemitchell** [comment]
@jeremy-w Could you rewrite the sentence more clearly? You kind of hinted at that with "but on if they weren't already licensed...".

**Comment by makkus** [comment]
I like that.

**Comment by mlinksva** [comment]
I see that "at least" was removed in c74dadff395090d35cfdfb286c59721526039374 though in the preceding discussion it seems that's what is intended https://github.com/licensezero/parity-public-license/issues/13#issuecomment-404929923

I see that @jeremy-w's proposed edit brings it back. I think the edit more clear than the current language, for including "at least", in addition to the question raised in the issue comment by @makkus.

**Comment by kemitchell** [comment]
I like the clarity of @jeremy-w's proposal, but am looking for a way to keep the license speaking in simple imperatives. When literally every other term of the license says "do this", one rule that says "this must be so" stands out, and could lead to the conclusion that something different was intended.

**Comment by kemitchell** [comment]
Taking a stab:

> To contribute software, publish all its source code, in the preferred form for making changes, through a freely accessible distribution system widely used for similar source code. If any part of the software is not already licensed on terms as permissive as those of this license, license it accordingly.

**Comment by mlinksva** [comment]
I had not noticed the consistent use of simple imperatives, but now that you have pointed it out, makes sense. I like your stab, but still think "**at least** as permissive" makes it clearer.

**Comment by kemitchell** [comment]
> To contribute software, publish all its source code, in the preferred form for making changes, through a freely accessible distribution system widely used for similar source code. If any part of the software is not already licensed on terms at least as permissive as those of this license, license it accordingly.

**Comment by kemitchell** [comment]
This language has been substantially revisited for Parity 7. As of 77c6bfa5f13f697a819ca65d5b50da85f012d8e9, `master` reads:

> ## Contribute
> 
> When this license requires you to [contribute](#contribute) software:
> 
> 1.  Publish all source code for the software, in the preferred form for making changes, through a freely accessible distribution system widely used for similar source code, so the contributor and others can find and copy it.
> 
> 2.  Make sure each part of the source code is available to the public under a license that gives as much or more permission as this one, such as [Blue Oak Model 1.0.0](https://blueoakcouncil.org/license/1.0.0), [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.html), [MIT](https://spdx.org/licenses/MIT.html), or [two-clause BSD](https://spdx.org/licenses/BSD-2-Clause.html).
> 
> 3.  Take these steps within thirty days.
> 
> 4.  Note that this license does _not_ allow you to change the license terms for this software.
