### ISSUE TITLE
Whose preferred form for making changes?

### ISSUE THREAD

**Issue by jeremy-w** [licensezero/parity-public-license#29]
Consider a Parity-licensed literate program. That’s pretty niche. But it would be the primary form the author is working in - clearly their current preference.

Suppose I think that’s a waste of time. I tangle their source (jargon for “ditch the plain language text and stitch all the code together in linear order”) and link it in and Parity license my cool new CLI tool.

I then tweak the tangled source directly. That’s my preferred form for making changes.

We have a disagreement in preferred form. It’d be work for anyone to figure out how to make my changes to the author’s original literate program. Am I obligated to do that, or can I just publish the edited, tangled code? (The original author will probably shed a tear at that.)

**Comment by kemitchell** [comment]
Parity largely follows GPLv2 section 1:

> The “source code” for a work means the preferred form of the work for making modifications to it. 

GPLv3 section 3 goes a little bit further, hinting that the preferred form is the input to any project-specific build pipelines, which also have to be shared, but only for "executable work":

> The source code for a work means the preferred form of the work for making modifications to it. For an executable work, complete source code means all the source code for all modules it contains, plus any associated interface definition files, plus the scripts used to control compilation and installation of the executable. However, as a special exception, the source code distributed need not include anything that is normally distributed (in either source or binary form) with the major components (compiler, kernel, and so on) of the operating system on which the executable runs, unless that component itself accompanies the executable.

Overall, I'm not sure how much benefit fleshing out "preferred form" would yield. Its main function is to prevent "contributing" files that are arguably "source code", but actually generated code, bytecode, compiled code, and so on.

**Comment by jeremy-w** [comment]
Agreed - this is edge-casey, and it's probably not worth trying to settle in the license text if it means adding a bunch of text. It would fall to licensor and licensee to sort out that disagreement if they cared to in this edge case.

It's all too easy for a programmer to forget that, unlike computers, the legal system can actually think for itself in the face of squishy specifications.
