### ISSUE TITLE
Rule 3, dev tools, and reverse engineering

### ISSUE THREAD

**Issue by jeremy-w** [licensezero/parity-public-license#31]
https://blog.licensezero.com/2018/11/24/parity-5.0.0.html#rule-3 talks about licensing software I debug using a Parity-licensed debugger.

It’s pretty common to aim debuggers at source you don’t have (understanding what’s happening in closed-source code) or that isn’t necessarily source you can relicense (third-party published library code, maybe under that Artistic License with more restrictive terms you discuss).

I also read the rule as using the verbs in the habitual mode. If I add it into my compilation pipeline, I’m definitely developing my software with it. If I snag a linter once, aim it at my code as a trial, find it mostly sucks but fix one issue it identified, and never touch it again, I don’t think of it as a tool I developed with. Maybe that’s my mistaken conception, and one use is all it takes?

I also read “run with” as ambiguously “run alongside the software” (as part of a software system - like aiming one of those old disk compression utilities of the DOS age at a server’s disk volume) or “use to run (interpret and execute) the software” like if a Virtual Machine were Parity-licensed. I’m not clear on the intended reading - maybe both?

**Comment by kemitchell** [comment]
Interesting. There's a tension here.

If you have a choice in whether the software you debug is open or closed, Parity wants it to be open. If you're working for someone who has the choice, Parity wants them to make it open.

If you have absolutely no way of making the software open---perhaps you're using a RE tool to create an open version of closed software---Parity wants to allow you to use that tool. But that's a hard line to draw.

**Comment by jeremy-w** [comment]
Maybe some sort of caveat around affecting only projects you can license, similar to that around patent grants being limited by the contributor's ability to act as grantor?

**Comment by kemitchell** [comment]
> Maybe some sort of caveat around affecting only projects you can license, similar to that around patent grants being limited by the contributor's ability to act as grantor?

We'd have to go further than that. For example: You're reversing a program your client has the right to license, but you don't.

**Comment by jeremy-w** [comment]
Does that situation not arise around patent grants, too?

**Comment by kemitchell** [comment]
The who-can-license question for patents looks much like the who-can-license question for copyrights.

**Comment by kemitchell** [comment]
Perhaps an exemption to Rule 3 for reverse engineering closed programs to make open alternatives?
