### ISSUE TITLE
Revisit Rule 5 for Clarification

### ISSUE THREAD

**Issue by kemitchell** [licensezero/parity-public-license#43]
https://github.com/licensezero/parity-public-license/pull/41#commitcomment-31902921

Current text:

> 5. Do not make any legal claim against anyone for infringing any patent claim they would infringe by using this software alone, accusing this software, with or without changes, alone or with other software.

**Comment by jeremy-w** [comment]
I think this is closed by df69499f793d3a0210fec8d60334d24b6b2300a4 ?

**Comment by kemitchell** [comment]
@jeremy-w Yessir!
