### ISSUE TITLE
GitHub example may now be confusing

### ISSUE THREAD

**Issue by mswilson** [licensezero/parity-public-license#49]
Regarding https://github.com/licensezero/parity-public-license/blob/master/README.md at cs dab0ad631c1916f835eb41790ee04f18d672a8b7

As of [2019-01-07]( https://github.blog/2019-01-07-new-year-new-github/), GitHub Free includes private repositories. But even before that, GitHub was free for public repositories, but those repositories do not have to be open source. Example: https://help.github.com/en/articles/licensing-a-repository

**Comment by kemitchell** [comment]
It's Friday!
