### ISSUE TITLE
Rule 3 and revisions

### ISSUE THREAD

**Issue by christianbundy** [licensezero/parity-public-license#52]
> 3. Contribute software you develop, deploy, monitor, or run with this software.

> To contribute software, publish all its source code, in the preferred form for making changes, through a freely accessible distribution system widely used for similar source code, and license contributions not already licensed to the public on terms as permissive as this license accordingly.

I might be taking this too literally, but it seems to me that this might require publishing all revisions. Am I reading this correctly?

For example, assume a linter licensed under the Parity license. If this linter runs on source code, I'd imagine that the Parity license would require that I contribute *that* software that my linter ran on, not some derivative source code that I'm ready to release a week later.

A text editor might make an even more interesting example, since I assume that you'd have to contribute the software that was originally opened by the editor *and* the software that the editor saved to the disk. Taking this to its logical extreme, I could imagine a scenario where you'd want to be careful about which files you edit with this editor since you'd have to contribute anything in those files (including API keys, etc).

Relevant: #31

**Comment by kemitchell** [comment]
This is a great question. It deserves a good answer. I’ll reply as soon as I can get around to it.

**Comment by kemitchell** [comment]
@christianbundy you've homed in on one of the key boundary-drawing problems in any copyleft license that wants to cover both distributed software, like installed applications, and software provided as a service, like web apps.

The original software copyleft licenses required sharing source code and license permission _only_ when you share copies of software with others. If you never distributed your changes or software, or only distributed them within your company, GPL never required you to share alike.

That rule was partly responsible for the "ASP Loophole", now sometimes called the "SaaS Loophole". You can take a GPL library, build a web service with it, provide the web service to millions of users, and so long as you don't send them the software to run for themselves in any way, you're free to keep your code closed. GPL wanted to give people the freedom to create and run "private changes" without sharing back. But the notion of "private changes" ended up covering a lot of very public software that just happened to get delivered as a service.

I would read Parity as you do: You have to release software that you build with Parity-licensed software, whether you planned to release it or not. That absolutism definitively closes the ASP Loophole. There's no arguing your code is just code you would have kept to yourself, because that just doesn't matter under Parity's share-alike rule.

**Comment by kemitchell** [comment]
@christianbundy somewhat after Parity, I began work on a slightly different license, the API Copyleft License, that includes an exception for prototypes. Here are the relevant bits of [the draft on `master`](https://github.com/kemitchell/api-copyleft-license/blob/76f94641b67cc9b4926e270489f932c9a0694332/license.md#prototypes):

> ## Copyleft
> 
> The purpose of this rule is to encourage cooperative development of this software, minimizing duplication of effort across competing substitutes.
> 
> With two exceptions, [Prototypes](#prototypes) and [Applications](#applications), you must contribute all changes and additions to this software, as well as all software that invokes this software's functionality, according to [Contributing](#contributing).  When in doubt, contribute the software.
> 
> ## Prototypes
> 
> The purpose of this exception to [Copyleft](#copyleft) is to allow private experimentation.
> 
> You need not contribute prototype changes, extensions, or applications that you do not end up using for more than fourteen calendar days, share with anyone else, or use to provide a service to anyone else.

**Comment by christianbundy** [comment]
Thanks for the thoughtful (and quick!) response. 

I think the prototype exception makes a lot of sense, and I'm having a hard time coming up with any loopholes that it might open. Do you think that something like the prototype exception would make sense for the Parity license? I'm not sure whether my "you have to release every revision" read of the current license is correct, but if so (and if you're open to a prototype exception or similar) I'd be happy to start a pull request.

**Comment by kemitchell** [comment]
I would read Parity 6 to require sharing everything immediately.

The loopholes under a rule like API Copyleft's Prototype section come right from the terms of that rule: "prototype", "share", "use to provide a service", and "anyone else". And of course the fourteen-day exception makes room for arguments about intermittent and one-time uses. For example, if the licensed code is a static analyzer and you run it on a closed codebase once, deriving all of the value of the analysis from that one run.

**Comment by christianbundy** [comment]
> I would read Parity 6 to require sharing everything immediately.

I suppose my concern is that this sounds like a license violation:

```console
$ echo "const x=42" > foo.js
$ parity-lint --fix foo.js
$ cat foo.js
const x = 42
$ rm foo.js
```

I'd be very hesitant to use any tool that made accidental copyright infringement so easy, so it seems like Parity-licensed tools would need to immediately upload anything that they "develop, deploy, monitor, or run" to avoid copyright infringement. I'd imagine that a Parity-licensed text editor would have to contribute software on every keypress (or save?), which I'd imagine is not the point of the license. Do you feel similarly, or am I misunderstanding? Apologies if I'm wasting your time on this, it's *very* possible that I'm chasing my own tail over a non-issue.

Thinking about this more, maybe the problem I'm describing is even triggered by rule 1:

> 1. Contribute changes and additions you make to this software.

I might be way off-base, but I can imagine violating this rule with:

```console
$ echo "\n" >> parity-lint/index.js
$ rm -rf parity-lint
```

This *absolutely* closes a handful of loopholes, but it feels like it replaces them with a trapdoor that might be very easy to fall through.

**Comment by kemitchell** [comment]
@christianbundy on the off chance you haven't run into yet, have you considered how the first three numbered rules interact with this later part of the license?

> You are excused for unknowingly breaking 1, 2, or 3 if you contribute as required, or stop doing anything requiring this license, within 30 days of learning you broke the rule.

**Comment by christianbundy** [comment]
Yeah, which I'm (incorrectly?) reading as:

> If you break the rules you have two options:
>
> - If you have every addition, modification, and combination of this software and all of the software you've developed, deployed, monitored, or run with this software, then you can contribute all of the above revisions and continue using this software.  
> - Otherwise, you're no longer allowed to use this software.

If my "you must contribute every revision" interpretation is correct, then this means that losing any revision of software touched by Parity-licensed software means losing access to the Parity-licensed software altogether. My understanding is that running `parity-vim foo.js && rm foo.js` legally gives me two options:

- remember exactly what the software looked like before `rm foo.js` and contribute that
- never use `parity-vim` again

It's unlikely that anyone would ever know about my license violation, but I've never used a copyright license where reasonable usage implies that users quietly violate the license and assume that nobody will ever know.
