### ISSUE TITLE
Clarifying Rule 5

### ISSUE THREAD

**Issue by larsgw** [licensezero/parity-public-license#53]
Similarly to #32, when reading this license it was unclear to me whether

> accusing this software, with or without changes, alone or with other software, of infringing any patent claim.

applied to "anyone" or "legal claim". In the first case, it reads

> 5. Do not make any legal claim against anyone **who is** accusing this software, with or without changes, alone or with other software, of infringing any patent claim.

This didn't really make sense to me, but I only figured out what was meant (the second case) when someone pointed me to the explanation of version 5. Maybe a comma would be warranted?

> 5. Do not make any legal claim against anyone, accusing this software, with or without changes, alone or with other software, of infringing any patent claim.

Also, does this rule allow legal claims against *entities* or is that covered by "anyone"?

**Comment by kemitchell** [comment]
I would read "anyone" to cover legal entities or individuals.

```
Do not make any legal claim
  against anyone
  accusing
    this software,
      with or without changes,
      alone or with other software,
    of infringing any patent claim.
```
If we drop the dependent-clause clarifications:

> Do not make any legal claim against anyone accusing this software of infringing any patent claim.

**Comment by kemitchell** [comment]
Closing, since the ongoing rewrite for Parity 7 replaces the language of original concern here.
