### ISSUE TITLE
make it possible to comply on common computer hardware

### ISSUE THREAD

**Issue by JanZerebecki** [licensezero/parity-public-license#60]
Common computer hardware contains firmware that you do not have the source to. Harder to avoid are e.g. disks (including sd-cards and usb-sticks) and USB cables.

> 2.  If you combine this software with other software, contribute that software.

Downloading thusly licensed software on such a computer reads to me as combining it with the firmware (and also all other software that is on the computer).

**Comment by kemitchell** [comment]
@JanZerebecki do USB cables have firmware?

**Comment by JanZerebecki** [comment]
Every USB-C cable that supports any of more than 3A power or USB 3.1 Gen1 or Gen2 or alternate modes (DisplayPort, etc.) needs a chip to announce this support. This is called Electronically Marked Cable Assembly. These chips usually have firmware that can be updated.

**Comment by kemitchell** [comment]
@JanZerebecki thanks! I did not know about chips in USB-C cables.

**Comment by kemitchell** [comment]
@JanZerebecki, returning to your question about the license:

I wouldn't read "combine" in the way you do, to cover, say, the firmware on a USB stick that happened to be plugged into a laptop running a Parity-licensed linter. Nor would I read it to require contributing the Linux operating system of that laptop under terms at least as permissive as Parity. But Parity isn't just supposed to be easier me to read, or for other lawyers to read. It should be easy to read and fairly clear to anyone, without requiring any technical terminology, legal jargon, or even any particularly tricky bits of English.

For what it's worth, I believe comments similar to yours led to this kind of language in GPLv3:

> The “Corresponding Source” for a work in object code form means all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work, including scripts to control those activities. However, it does not include the work’s System Libraries, or general-purpose tools or generally available free programs which are used unmodified in performing those activities but which are not part of the work. [...]

GPL also defines "System Libraries" using another definition, "Major Component". In case it's not familiar: Corresponding Source defines the source code that GPLv3 requires sharing alike.

That complicated exception has become a potential loophole, especially in AGPLv3, now that applications are routinely deployed and combined in containers with their own, discreet copies of the relevant operating system.

If you use a Parity-licensed linter, compiler, library, or framework to write firmware, Parity should require contributing the source code for that firmware.  If you'reusing a Parity-licensed framework to write a GUI app to manage a device that comes with firmware, Parity should require contribute that firmware, too.

**Comment by JanZerebecki** [comment]
I hadn't yet heard of the "System Libraries"-exception being used as a loophole. Do you have examples?

> Nor would I read it to require contributing the Linux operating system of that laptop under terms at least as permissive as Parity.

How does this reading not create the same loopholes as being more specific, e.g. with the System Libraries exception?

Is the intent to cover deployment scripts used for a work under Parity? (One of the SaaS loopholes.)
If it is, what part of Parity do you read as doing that?

> 3. Contribute other software you develop, deploy, monitor, or run with this software.

As this part of the license only covers the other way around, using deployment script under Parity makes what is deployed covered.

**Comment by kemitchell** [comment]
Prior versions of parity included “larger program” and “larger application” in rule 2. We found those terms unintentionally limiting.

**Comment by kemitchell** [comment]
@JanZerebecki thanks again for this feedback. As you'll see on `master`, we've substantially rewritten the copyleft rule, without the word "combine".

If you think your point is still a concern under the new language, please feel free to respond here again, or to open a new issue!

**Comment by JanZerebecki** [comment]
Yes those changes resolve this issue, thank you.

It also makes it clear that it does not cover deployment scripts used for a work under Parity, thus does not close the SaaS loophole.

( New version I read: https://github.com/licensezero/parity-public-license/blob/335364428b2244dc497c18882bd5fc169b6e12f0/LICENSE.md old version the issue was opened for: https://github.com/licensezero/parity-public-license/blob/9b84be4c805bbcdaf12bf2d4883645fcfb8df564/LICENSE.mustache .)

**Comment by kemitchell** [comment]
> It also makes it clear that it does not cover deployment scripts used for a work under Parity, thus does not close the SaaS loophole.

I do not agree. See https://paritylicense.com/versions/7.0.0.html#copyleft
