### ISSUE TITLE
List format for prototype conditions?

### ISSUE THREAD

**Issue by makkus** [licensezero/parity-public-license#62]
> You need not contribute prototype changes, additions, or other software that you do not end up using for more than thirty calendar days, sharing outside the development team working on the prototype, or using to provide a service to anyone else.

Ok, this might just be me, and you might have a very good reason to not do that, but when reading this I just thought it'd be easier to parse (for me at least) if it was formatted as list, something like:

> You need not contribute prototype changes, additions, or other software that you:
>
> -  do not end up using for more than thirty calendar days
> - don't share outside the development team working on the prototype
> - or use to provide a service to anyone else

P.S. sorry, that was meant to go into the 'Simplify Copyleft' pull request thread (but not sure if that'd be the right place either - so I'm leaving it here for now)

**Comment by makkus** [comment]
Actually, upon further thinking, I think it was just the 'sharing...' and 'using...' in the 2nd and 3rd conditions that threw me. I think there are 'it'-s missing. Maybe the 'do not end up' does not need to refer to those two conditions, and it could just read:

| You need not contribute prototype changes, additions, or other software that you do not end up using for more than thirty calendar days, don't share outside the development team working on the prototype, or use to provide a service to anyone else.

**Comment by kemitchell** [comment]
It's a list. Let's make it a list!
