### ISSUE TITLE
Avoiding CLAs with Parallel Licensing?

### ISSUE THREAD

**Issue by Avi-D-coder** [licensezero/parity-public-license#64]
In the [guide](https://guide.licensezero.com/#parallel-licensing) it states:
> ask contributors to license their work under Blue Oak, and append the text of that license to your project’s LICENSE file with a note that others’ contributions come under that license.

This brings up several questions:
1. Can the permissive license be in a separate file, so long as the note is at prepended to the contributor license and perhaps the file name?
2. Is a CLA bot or form needed when using parallel licensing?

**Comment by kemitchell** [comment]
@Avi-D-coder, thanks for your interest.

There aren't any hard rules about how to get licenses from contributors, or how to document those licenses. The guide mentions `LICENSE` files because I think that's the most common convention for expressing license terms.

**Comment by Avi-D-coder** [comment]
If a project is only under parity, I assume a CLA is not needed, so long as re-licensing is not a concern?

**Comment by kemitchell** [comment]
@Avi-D-coder if your intention is to make sure that _anyone_ who uses the code follows Parity's rules, all contributors can and should contribute under Parity terms.

However, it's still important to get a record showing that each contributor chooses Parity for their work. You may also want to use CLAs to ensure that someone can relicense the project as a whole, perhaps to a future Parity 7 or another license, without getting specific permission from every contributor.
