### ISSUE TITLE
Is this license usable in the App store?

### ISSUE THREAD

**Issue by AlexMax** [licensezero/parity-public-license#73]
Just what it says on the tin.  Does Apple count as a license receiver?

**Comment by kemitchell** [comment]
@AlexMax could you link me to the latest Apple terms on point?

**Comment by AlexMax** [comment]
I am not an app developer myself, so I am unfamiliar with which terms of service would be applicable to copyleft software.  I did find a site on Apple's website with "guidelines" after a quick Google search, but I don't think those are the actual legal terms of service.

This is the FSF's article about pursuing compliance with GNU Go dated from 2010, with their reasoning as to why they think the GPL doesn't comply with app store guidelines of that time:

https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement

What I'm unsure about is if those same arguments would apply to Parity, not being a FSF license and written in non-legalese.  I'm also unsure if Apple's specific wording has changed in a way that would make things more difficult to comply with.

And just so we're on the same page, I've been wanting an app-store safe strong copyleft license for a while.  To my mind, the App Store behaves like a storefront, and I don't particularly care about any extra steps that Apple might take to get the product from the developers machine into the store.  As long as other _developer_'s obey the copyleft, I don't care if the digital storefront does.

**Comment by kemitchell** [comment]
The FSF's point seems to have been that their own licenses prohibit adding any additional restrictions to the license terms for the software, while Apple's terms for the App Store at the time imposed some additional rules around acceptable use cases and security.

No version of Parity to date has any "no additional rules" section of the kind found in the recent FSF licenses.
