### ISSUE TITLE
License obligations potentially watered down through forks of forks.

### ISSUE THREAD

**Issue by Iolaum** [licensezero/parity-public-license#76]
I was reading the license text and focused on this particularly:

```
Make sure every part of the source code is available under this license or another license that
allows everything this license does, such as the Blue Oak Model License 1.0.0, the Apache License 2.0,
the MIT license, or the two-clause BSD license.
```

I was wondering if the following scenario can occur:

1. Entity A creates project1 and licenses the code with parity v7.0.0
2. Entity B forks project1 into project2 and licenses the code under Apache License 2.0
3. Entity C forks project2 into project3 and keeps the code proprietary.

I am making two key assumptions here:
- The intent of the license is to keep downstream forks open source (free software?) as is the original project, much like the (A)GPLv3 license intends.
- The original creator of the project intends for downstream forks to also be open source so that they can incorporate their changes in the original project if they chose to.

Please correct me if the above assumptions are wrong or don't fit the scope of the license.

The way I read the license the scenario above is allowed. Step 2 is the crucial link. Is my understanding correct?

**Comment by orlandohill** [comment]
Step 2 is not permitted. Parity doesn't grant the right to change the
license of the software. See point 4 of 'Contribute'.

The text you quote is from point 2 of 'Contribute'. In the case of a fork,
the software to be contributed would be "changes or additions" to the
original software. See 'Copyleft'. If I understand correctly, changes would
need to remain under Parity, but additions (new code that only adds
functionality) could be released under a permissive license.

>

**Comment by Iolaum** [comment]
I see, thanks for clarifying.
