### ISSUE TITLE
Clarify wording on Copyright and Patent sections

### ISSUE THREAD

**Issue by skullbunnygalaxy** [licensezero/parity-public-license#78]
> ## Copyright
> The contributor licenses you to do everything with this software that would otherwise infringe their copyright in it.
> ## Patent
> The contributor licenses you to do everything with this software that would otherwise infringe any patents they can license or become able to license.

I kept misreading "contributor licenses" [noun verb] as "contributor license" [adjective noun] and had to re-read it multiple times before I read it correctly. Most of the license is worded with "you verb" whereas the wording here changes format to "the contributor verb you." I would like to suggest adjusting the wording here to make it easier to parse.

Example of adjusted wording: As a contributor, you agree to license any contributions you have made with this software that would otherwise infringe your copyright in it.

**Comment by kemitchell** [comment]
@skullbunnygalaxy, thanks so much for this feedback!

I am seeing now, thanks to you, that the overwhelming majority of people will not have read or heard "license" as a verb very often. In software licensing, however, they will have seen it as a verb an awful lot.

Do you think it would help readers to rephrase like so?:

> ## Copyright
> 
> The contributor <del>licenses you</del><ins>gives you a license</ins> to do everything with this software that would otherwise infringe their copyright in it.
> 
> ## Patent
> 
> The contributor <del>licenses you</del><ins>gives you a license</ins> to do everything with this software that would otherwise infringe any patents they can license or become able to license.

**Comment by skullbunnygalaxy** [comment]
Yes, I think that would help.

**Comment by kemitchell** [comment]
Closing per comment here: https://github.com/licensezero/parity-public-license/pull/79#issuecomment-1020671810
