### ISSUE TITLE
Use of Unrelated Patents

### ISSUE THREAD

**Issue by lngns** [licensezero/parity-public-license#82]
> Patent  
> The contributor licenses you to do everything with this software that would otherwise infringe any patents they can license or become able to license.

If I hold patents and then make a contribution to a project under Parity that does not fall under those patents, then you can do anything with the project that infringe on my patents.  

Meanwhile Apache 2 says

> Each Contributor hereby grants to You [...] patent license [...] where such license applies only to those patent claims licensable by such Contributor that are necessarily infringed by their Contribution(s) alone or by combination of their Contribution(s) with the Work to which such Contribution(s) was submitted.

and then defines "Contribution" as

> "Contribution" shall mean any work of authorship, including the original version of the Work and any modifications or additions to that Work or Derivative Works thereof, that is intentionally submitted to Licensor for inclusion in the Work.

explicitly saying that only patents that may cover this contribution are licensed to you.

Is my interpretation wrong? Or is it the desired effect?

**Comment by kemitchell** [comment]
This is the desired effect.

Do not both contribute to a Parity project, thereby encouraging its adoption and use, and then turn around and sue its maintainers or users for patent infringement.
